[package]
name = "keymoji"
version = "0.1.0"
authors = ["Raphael Tang <raphpb1912@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
web-view = "0.7"
winit = "0.24.0"
clipboard = "0.5.0"
sysinfo = "0.18.2"